// Generated by ReScript, PLEASE EDIT WITH CARE


function showMsg(logseq, content, statusOpt, opts, param) {
  var status = statusOpt !== undefined ? statusOpt : "success";
  return logseq.showMsg(content, status, opts);
}

var UIProxy = {
  showMsg: showMsg
};

var isBlockEntity = (v => ["content", "page"].every(k => Object.prototype.hasOwnProperty.call(v, k)));

function classify(v) {
  if (isBlockEntity(v)) {
    return {
            TAG: /* BlockEntity */0,
            _0: v
          };
  } else {
    return {
            TAG: /* PageEntity */1,
            _0: v
          };
  }
}

var BlockOrPageEntity = {
  classify: classify
};

var EditorProxy = {};

function classify$1(v) {
  if (typeof v === "string") {
    return {
            TAG: /* String */0,
            _0: v
          };
  } else {
    return {
            TAG: /* Bool */1,
            _0: v
          };
  }
}

var StringOrBool = {
  classify: classify$1
};

var AppProxy = {};

var LSUserPlugin = {};

export {
  UIProxy ,
  BlockOrPageEntity ,
  EditorProxy ,
  StringOrBool ,
  AppProxy ,
  LSUserPlugin ,
}
/* No side effect */
